// <auto-generated />
using System;
using System.Text.Json;
using Caribe.AccesoDatos.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Caribe.AccesoDatos.Migrations
{
    [DbContext(typeof(CaribeContext))]
    partial class CaribeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Caribe.AccesoDatos.Identidad.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("InvitadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("invitado_por_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Accion")
                        .HasColumnType("smallint")
                        .HasColumnName("accion");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("DatosAntes")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_antes");

                    b.Property<JsonDocument>("DatosDespues")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_despues");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entidad_id");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("UsuarioId", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_auditoria_usuario_id_creado_en");

                    b.HasIndex("Entidad", "EntidadId", "CreadoEn")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_auditoria_entidad_entidad_id_creado_en");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.ConfiguracionFinanciamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ActualizadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("actualizado_por_id");

                    b.Property<short>("PlazoMaximoMeses")
                        .HasColumnType("smallint")
                        .HasColumnName("plazo_maximo_meses");

                    b.Property<short>("PlazoMinimoMeses")
                        .HasColumnType("smallint")
                        .HasColumnName("plazo_minimo_meses");

                    b.Property<string>("PlazosDisponibles")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("plazos_disponibles");

                    b.Property<decimal>("PorcentajePrima")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_prima");

                    b.Property<decimal>("TasaAnual")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tasa_anual");

                    b.Property<string>("TextoLegal")
                        .HasColumnType("text")
                        .HasColumnName("texto_legal");

                    b.HasKey("Id")
                        .HasName("pk_configuracion_financiamiento");

                    b.ToTable("configuracion_financiamiento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = false,
                            ActualizadoEn = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PlazoMaximoMeses = (short)36,
                            PlazoMinimoMeses = (short)12,
                            PlazosDisponibles = "12,24,36",
                            PorcentajePrima = 50m,
                            TasaAnual = 0m
                        });
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.EstadisticaHistorica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<int>("Cerradas")
                        .HasColumnType("integer")
                        .HasColumnName("cerradas");

                    b.Property<int>("Contactadas")
                        .HasColumnType("integer")
                        .HasColumnName("contactadas");

                    b.Property<int>("Descartadas")
                        .HasColumnType("integer")
                        .HasColumnName("descartadas");

                    b.Property<int>("EnProceso")
                        .HasColumnType("integer")
                        .HasColumnName("en_proceso");

                    b.Property<short>("Mes")
                        .HasColumnType("smallint")
                        .HasColumnName("mes");

                    b.Property<int>("Nuevas")
                        .HasColumnType("integer")
                        .HasColumnName("nuevas");

                    b.Property<int>("Purgadas")
                        .HasColumnType("integer")
                        .HasColumnName("purgadas");

                    b.HasKey("Id")
                        .HasName("pk_estadisticas_historicas");

                    b.HasIndex("Anio", "Mes")
                        .IsUnique()
                        .HasDatabaseName("ix_estadisticas_historicas_anio_mes");

                    b.ToTable("estadisticas_historicas", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Invitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("InvitadoPorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("invitado_por_id");

                    b.Property<DateTimeOffset?>("RevocadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocada_en");

                    b.Property<short>("Rol")
                        .HasColumnType("smallint")
                        .HasColumnName("rol");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("UsadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usada_en");

                    b.HasKey("Id")
                        .HasName("pk_invitaciones");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_invitaciones_email")
                        .HasFilter("usada_en IS NULL AND revocada_en IS NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitaciones_token_hash");

                    b.ToTable("invitaciones", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_marcas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_marcas_nombre");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_modelos");

                    b.HasIndex("MarcaId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_modelos_marca_id_nombre");

                    b.ToTable("modelos", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<string>("ReemplazadoPor")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reemplazado_por");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId", "ExpiraEn")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id_expira_en")
                        .HasFilter("revocado_en IS NULL");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("AnioDesde")
                        .HasColumnType("smallint")
                        .HasColumnName("anio_desde");

                    b.Property<DateTimeOffset?>("ArchivadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archivada_en");

                    b.Property<string>("AsignadaAId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("asignada_a_id");

                    b.Property<DateTimeOffset?>("AtendidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atendida_en");

                    b.Property<short?>("Combustible")
                        .HasColumnType("smallint")
                        .HasColumnName("combustible");

                    b.Property<bool>("Consentimiento")
                        .HasColumnType("boolean")
                        .HasColumnName("consentimiento");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Detalles")
                        .HasColumnType("text")
                        .HasColumnName("detalles");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<short>("FormaPago")
                        .HasColumnType("smallint")
                        .HasColumnName("forma_pago");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origen");

                    b.Property<string>("MarcaTexto")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("marca_texto");

                    b.Property<string>("ModeloTexto")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modelo_texto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<short>("Origen")
                        .HasColumnType("smallint")
                        .HasColumnName("origen");

                    b.Property<short?>("PlazoMesesInteres")
                        .HasColumnType("smallint")
                        .HasColumnName("plazo_meses_interes");

                    b.Property<decimal?>("PresupuestoMax")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("presupuesto_max");

                    b.Property<decimal?>("PresupuestoMin")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("presupuesto_min");

                    b.Property<short?>("Transmision")
                        .HasColumnType("smallint")
                        .HasColumnName("transmision");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("vehiculo_id");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_solicitudes");

                    b.HasIndex("VehiculoId")
                        .HasDatabaseName("ix_solicitudes_vehiculo_id");

                    b.HasIndex("Estado", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_solicitudes_estado_creado_en")
                        .HasFilter("archivada_en IS NULL");

                    b.HasIndex("Whatsapp", "CreadoEn")
                        .HasDatabaseName("ix_solicitudes_whatsapp_creado_en");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.SolicitudNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nota");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_solicitud_notas");

                    b.HasIndex("SolicitudId", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_solicitud_notas_solicitud_id_creado_en");

                    b.ToTable("solicitud_notas", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.TokenRecuperacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("IpSolicitud")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_solicitud");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens_recuperacion");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_recuperacion_token_hash");

                    b.HasIndex("UsuarioId", "CreadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_tokens_recuperacion_usuario_id_creado_en");

                    b.ToTable("tokens_recuperacion", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaFinanciamiento")
                        .HasColumnType("boolean")
                        .HasColumnName("acepta_financiamiento");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("color");

                    b.Property<short>("Combustible")
                        .HasColumnType("smallint")
                        .HasColumnName("combustible");

                    b.Property<decimal>("CostoFlete")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_flete");

                    b.Property<decimal>("CostoImpuestos")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_impuestos");

                    b.Property<decimal>("CostoTramites")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_tramites");

                    b.Property<decimal>("CostoVehiculo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("costo_vehiculo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreadoPorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("creado_por_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Destacado")
                        .HasColumnType("boolean")
                        .HasColumnName("destacado");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<decimal>("Honorario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("honorario");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("integer")
                        .HasColumnName("kilometraje");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<int>("ModeloId")
                        .HasColumnType("integer")
                        .HasColumnName("modelo_id");

                    b.Property<decimal>("PrecioPublicado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_publicado");

                    b.Property<DateTimeOffset?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<short>("Traccion")
                        .HasColumnType("smallint")
                        .HasColumnName("traccion");

                    b.Property<short>("Transmision")
                        .HasColumnType("smallint")
                        .HasColumnName("transmision");

                    b.Property<DateTimeOffset?>("VendidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vendido_en");

                    b.Property<short>("VigenciaDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)7)
                        .HasColumnName("vigencia_dias");

                    b.Property<int>("Visitas")
                        .HasColumnType("integer")
                        .HasColumnName("visitas");

                    b.HasKey("Id")
                        .HasName("pk_vehiculos");

                    b.HasIndex("ModeloId")
                        .HasDatabaseName("ix_vehiculos_modelo_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_vehiculos_slug");

                    b.HasIndex("Estado", "PublicadoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_vehiculos_estado_publicado_en")
                        .HasFilter("estado IN (1, 2)");

                    b.HasIndex("MarcaId", "ModeloId", "PrecioPublicado")
                        .HasDatabaseName("ix_vehiculos_marca_id_modelo_id_precio_publicado");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.VehiculoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EsPortada")
                        .HasColumnType("boolean")
                        .HasColumnName("es_portada");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("url");

                    b.Property<string>("UrlThumb")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("url_thumb");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_vehiculo_fotos");

                    b.HasIndex("VehiculoId")
                        .IsUnique()
                        .HasDatabaseName("ix_vehiculo_fotos_vehiculo_id")
                        .HasFilter("es_portada = true");

                    b.HasIndex("VehiculoId", "Orden")
                        .HasDatabaseName("ix_vehiculo_fotos_vehiculo_id_orden");

                    b.ToTable("vehiculo_fotos", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_rol_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_rol_claims_role_id");

                    b.ToTable("rol_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_claims_user_id");

                    b.ToTable("usuario_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_usuario_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_logins_user_id");

                    b.ToTable("usuario_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_usuario_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuario_roles_role_id");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usuario_tokens");

                    b.ToTable("usuario_tokens", (string)null);
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Modelo", b =>
                {
                    b.HasOne("Caribe.Dominio.Entidades.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modelos_marcas_marca_id");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Solicitud", b =>
                {
                    b.HasOne("Caribe.Dominio.Entidades.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitudes_vehiculos_vehiculo_id");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.SolicitudNota", b =>
                {
                    b.HasOne("Caribe.Dominio.Entidades.Solicitud", "Solicitud")
                        .WithMany("Notas")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitud_notas_solicitudes_solicitud_id");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Vehiculo", b =>
                {
                    b.HasOne("Caribe.Dominio.Entidades.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculos_marcas_marca_id");

                    b.HasOne("Caribe.Dominio.Entidades.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculos_modelos_modelo_id");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.VehiculoFoto", b =>
                {
                    b.HasOne("Caribe.Dominio.Entidades.Vehiculo", "Vehiculo")
                        .WithMany("Fotos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculo_fotos_vehiculos_vehiculo_id");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Caribe.AccesoDatos.Identidad.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Caribe.AccesoDatos.Identidad.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_roles_role_id");

                    b.HasOne("Caribe.AccesoDatos.Identidad.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Caribe.AccesoDatos.Identidad.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Solicitud", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Caribe.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
